apiVersion: v1
kind: Service
metadata:
  name: manual-server
spec:
  type: NodePort
  selector:
    app: manual-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080  
